Smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,45 +3,47 @@ orbs:
   slack: circleci/slack@4.12.1
 
 commands:
-  notify_on_failure:
-    steps:
-      - slack/notify:
-          event: fail
-          channel: cicd-udacity-project
-          template: basic_fail_1
-  install_aws_cli:
+  install_awscli:
+    description: Install AWS CLI v2
     steps:
       - run:
-          name: Install AWS CLI
+          name: install aws cli v2
           command: |
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
+
   install_ansible:
-    description: Install Ansible on Ubuntu
+    description: install ansible
     steps:
       - run:
-          name: Install Ansible
+          name: install ansible
           command: |
             sudo apt update
-            sudo apt install software-properties-common
+            sudo apt install software-properties-common -y
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible -y
   install_nodejs:
-    description: Install Node.js 13
+    description: install NodeJS 13
     steps:
       - run:
-          name: Install Node.js 13
+          name: install NodeJS 13
           command: |
-            # First: we install lts version as base
             curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
             sudo apt install -y nodejs
-            # Then: we install n version manager to get to required version
+
             sudo npm install --global n
             sudo n 13.8.0
+  notify_on_failure:
+    steps:
+      - slack/notify:
+          event: fail
+          channel: cicd-application
+          template: basic_fail_1
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
+      # Add parameter here
       Workflow_ID:
         type: string
         default: ${CIRCLE_WORKFLOW_ID:0:7}
@@ -50,35 +52,31 @@ commands:
           name: Destroy environments
           when: on_fail
           command: |
+            # Your code here
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.Workflow_ID >>
             aws s3 rm s3://udapeople-<< parameters.Workflow_ID >> --recursive
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.Workflow_ID >>
+
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
+      # Add parameter here
       Workflow_ID:
         type: string
         default: ${CIRCLE_WORKFLOW_ID:0:7}
     steps:
       - run:
           name: Revert migrations
+          # Add when this will run
           when: on_fail
           command: |
-            # Install Node.js 13
-            # First: we install lts version as base
-            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-            sudo apt install -y nodejs
-            # Then: we install n version manager to get to required version
-            sudo npm install --global n
-            sudo n 13.8.0
-            SUCCESS=$(curl https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
-            # Revert database changes
-            if [[ $SUCCESS==1 ]]
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl --insecure https://kvdb.io/MaGP6Xi8L6533u3645QfAG/migration_<< parameters.Workflow_ID >>)
+            if(( $SUCCESS==1 ));
             then
               cd ~/project/backend
               npm install
-              npm run migrations:revert > revert_migrations_dump.txt
-              cat revert_migrations_dump.txt
+              npm run migration:revert
             fi
 
 jobs:
@@ -366,42 +364,45 @@ jobs:
 
   smoke-test:
     docker:
-      - image: amazon/aws-cli
+      - image: mareimorsy/aws-node
     steps:
+
       - checkout
-      - run:
-          name: Frontend smoke test.
-          command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-              echo "It worked!"
-              exit 0
-            else
-              echo "Rolling Back"
-              exit 1
-            fi
+      
       - run:
           name: Backend smoke test.
           command: |
-            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            URL="http://${BACKEND_PUBLIC_IP}:3030/api/status"
-            echo ${URL}
-
-            if curl -s --head ${URL}
+            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            --filters Name=tag:Project,Values=Udapeople \
+            --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            
+            BACKEND_URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            
+            if curl -s $BACKEND_URL | grep "ok"
             then
-              echo "It worked!"
+              echo "Backend works"
               exit 0
             else
-              echo "Rolling Back"
               exit 1
             fi
-      # - notify-on-failure
-      # - destroy-environment:
-      #     Workflow_ID: "${CIRCLE_WORKFLOW_ID:0:5}"
-      # - revert-migrations:
-      #     Workflow_ID: "${CIRCLE_WORKFLOW_ID:0:5}"
+            pwd
+      - destroy-environment   
+      - revert-migrations
+
+      - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations
 
   cloudfront-update:
     docker:
@@ -519,7 +520,7 @@ workflows:  # create workflows
       #     requires: [run-migrations]
       - smoke-test
       #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update
+      # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
       #     requires: [cloudfront-update]
